language: python
python:
  - "3.6"
before_install:
  - './ci/setup.sh'
install:
  - pip install -r src/requirements.txt
script:
  - 'make test'
  - 'make image'
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u _json_key -p "${GCP_DOCKER_REGISTRY_CREDS}" https://gcr.io
      make push-image ;
    fi

