language: python
python:
- '3.6'
before_install:
- openssl aes-256-cbc -K $encrypted_f98747a369fb_key -iv $encrypted_f98747a369fb_iv
  -in gcs_creds.json.enc -out gcs_creds.json -d
- "./ci/setup.sh"
install:
- pip install -r src/requirements.txt
script:
- make test
- make image
deploy:
  provider: gae
  keyfile: "gcs_creds.json"
  project: "dndonations-176523"
  on: master
